config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "omniauth_callbacks"}

  resources :home
  resources :posts do
    resources :comments
  end

  root "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    can   :update, Post do |post|
          post.user == user
          can  :destroy, Comment do |comment|
                comment.user == user
                post.user == user
          end
    end

    can  :update, Comment do |comment|
          comment.user == user
    end

    can   :destroy, Post do |post|
          post.user == user
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  # Include default devise modules. Others available are:
  #
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable, :timeoutable,
         :omniauthable, :omniauth_providers => [:facebook, :google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def after_sign_in_path_for(resource)
      super resource
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comments_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: 'Comment was successfully created.' }
      else
        redirect_to :back
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id]).destroy
    redirect_to :back
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comments_params)
        format.html { redirect_to post_path(params[:post_id]), notice: 'Comment successfully updated.' }

      end
    end
  end

  private
    def comments_params
      params.require(:comment).permit(:text)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

      if user_signed_in?
          redirect_to home_path(current_user)
      else
          redirect_to new_user_session_path
      end

  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"].except("extra")
        redirect_to new_user_registration_url
      end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @user = current_user
    @post = @user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
   @user = User.find_or_create_from_auth_hash(auth_hash)
   self.current_user = @user
   redirect_to '/'
 end

 protected

 def auth_hash
   request.env['omniauth.auth']
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @comment], class: "form-horizontal") do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field form-group">
    <%= f.label :text , class: "control-label" %><br>
    <%= f.text_area :text, class: "form-control", rows: 10 %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-raised btn-primary" %>
  </div>

<% end %>

app/views/comments/edit.html.erb
<div class="container">
  <%= link_to '<div id="circle-left"><span>Back</span></div>'.html_safe, posts_path %>
  <div class="row">
      <div class="list-item-container">
      <div class="list-item-header" style="margin-top:50px;">
          <h1>Edit Comment</h1>

          <%= render 'form' %>

      </div>
    </div>
  </div>
</div>


          <%= link_to 'Show', @post %> |
          <%= link_to 'Back', posts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/show.html.erb
  <div class="vertical-center">
    <div class="jumbotron-center">
      <p class="jumbo-title"> <span class="jumbo-user-name"><%= @user.name %></span> </p>
      <span class="jumbo-content">Did you already do something today? :)</span><br><br>

      <% if(@user.id == current_user.id) %>
      <%= link_to 'Share', '#animatedModal', class: 'btn btn-raised btn-primary btn-lg' , id: 'new'%>
      <%= link_to 'Explore', posts_path , class: 'btn btn-raised btn-primary btn-lg' %>
      <% end %>

    </div>

      <div id="animatedModal" >
        <div style="" class="modal-content vertical-center ">
          <div class="jumbotron-center">
            <div class="close-animatedModal">
              <i class="fa fa-times-circle-o fa-5x"></i>
            </div>


            <%= form_for(@post) do |f| %>
              <% if @post.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

                  <ul>
                  <% @post.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="form-group label-static">
                <p class="jumbo-content">
                                          Getting started is easy – just fill in the blanks below <br>
                                          and get to see all your posts. How exciting!</p>
                <%= f.text_field :title, class: 'modal-textfield', placeholder: 'Title' %><br>

                <%= f.text_area :content, class: "form-control", class: 'modal-textfield', rows: 8, placeholder: 'Your Thoughts'  %>
              </div>

              <div class="actions">
                <%= f.submit class: 'btn btn-primary btn-raised' %>
              </div>


            </div>

            <% end %>

          </div>
      </div>
  </div>
  <%= javascript_include_tag 'animatedModal' , 'data-turbolinks-track' => true %>
  <script>
    $("#new").animatedModal({
      animatedOut:'bounceOut',
      color:'#A26BEF'
    });

  </script>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dosomething</title>

  <%= stylesheet_link_tag    'http://fezvrasta.github.io/bootstrap-material-design/dist/css/bootstrap-material-design.css' %>
  <%= stylesheet_link_tag    'http://fezvrasta.github.io/bootstrap-material-design/dist/css/ripples.min.css' %>
  <%= stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/animate.css/3.2.0/animate.min.css' %>
  <%= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Roboto:300,400,500,700' %>
  <%= stylesheet_link_tag    'application' , 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' , 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' , 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<style>

</style>


<body style="justify-content: center;">

<% if user_signed_in? %>

        <div class="item-right">
          <span><%= link_to current_user.email, home_path(current_user) %></span>
          <%= link_to '<i style="font-size:20px" class="fa fa-power-off"></i>'.html_safe, destroy_user_session_path, method: :delete %>
        </div>

<% end %>
      

<%= yield %>

<div id="snackbar"></div>


</body>

<%= javascript_include_tag    'snackbar' , 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'http://fezvrasta.github.io/bootstrap-material-design/dist/js/material.min.js'  %>
<%= javascript_include_tag 'http://fezvrasta.github.io/bootstrap-material-design/dist/js/ripples.min.js'  %>

</html>

<script>
  $(function () {
    $.material.init();
  });

  $( document ).ready(function() {
    var content = "<%= notice %>"
    if (content){
      var snackbar = document.getElementById("snackbar")
      snackbar.innerHTML = content
      snackbar.className = "show";
      setTimeout(function(){ snackbar.className = snackbar.className.replace("show", ""); }, 3000);
    }

  });

</script>

app/views/posts/_form.html.erb
<%= form_for(@post, class: "form-horizontal") do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title , class: "control-label" %><br>
    <%= f.text_field :title  , class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :content , class: "control-label" %><br>
    <%= f.text_area :content, class: "form-control", rows: 10 %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-raised btn-primary" %>
  </div>

<% end %>
<%= debug(@post) %>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
      <div class="list-item-container">
      <div class="list-item-header">
          <h1>Edit Post</h1>

          <%= render 'form' %>

      </div>
    </div>
  </div>
</div>


          <%= link_to 'Show', @post %> |
          <%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container container-posts">
  <div id="circle"><span>Jump & Smile</span></div>
  <div class="row">
    <div class="col-lg-12">
      <%= link_to 'New Post', new_post_path, class: "btn btn-raised btn-primary pull-right" %><br>
      <% @posts.each do |post| %>
      <div class="list-item-container">
        <div class="list-item-header">
          <b>
            <h1 class="list-item-title">
              <%= link_to post.title.html_safe, post  %>
              <% if can? :update, post %>
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_post_path(post)  %>
              <% end %>
              <% if can? :destroy, post %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, post, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </h1>

          </b>
          <span>
            Wordings By: <%= link_to post.user.email, home_path(post.user.id) %>
          </span>
        </div>

        <div class="list-item-content">
          <%= post.content %>
        </div>
        <hr>
      </div>
      <% end %>
    </div>
  </div>
</div>
<br>

app/views/posts/new.html.erb
<div class="container">
  <%= link_to '<div id="circle-left"><span>Back</span></div>'.html_safe, posts_path %>
  <div class="row">
      <div class="list-item-container">
        <div class="list-item-header" style="margin-top:50px;">
          <h1>New Post</h1>

            <%= render 'form' %>

        </div>
      </div>
    </div>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container">
  <%= link_to '<div id="circle-left"><span>Back</span></div>'.html_safe, posts_path %>
  <div class="row">
    <div class="col-lg-12">
      <div class="list-item-container">
        <div class="list-item-header">
          <b>
            <h1 class="post-title">
              <%= link_to @post.title.html_safe, @post  %>
              <% if can? :update, @post %>
              <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_post_path(@post)  %>
              <% end %>
              <% if can? :destroy, @post %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, @post, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
              <span style="display:block">Wordings By: <%= link_to @post.user.email, home_path(@post.user.id) %></span>
            </h1><br>

          </b>

        </div>

        <div class="post-content">
          <%= @post.content %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-7 comments">
      <h2> <%= @post.comments.count %> comments </h2>
      <% @post.comments.each do |comment| %>
        <b><%= link_to comment.user.name, home_path(comment.user.id) %></b> - <%= comment.user.created_at.strftime("%m/%d/%Y") %>
          <% if can? :update, comment %>
          <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_post_comment_path(post_id: @post.id ,id: comment.id)  %>
          <% end %>
          <% if can? :destroy, comment %>
          <%= link_to '<i class="fa fa-trash"></i>'.html_safe, post_comment_path(post_id: @post.id ,id: comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        <br>
        <p><%= comment.text %></p><br><br>
      <% end %>
    </div>

    <div class="col-lg-5 comments has-success">
      <h1> Leave a Comment </h1>
      <%= form_for([@post, @post.comments.build]) do |f| %>
        <%= f.text_area :text , class: "form-control ", rows: 10 ,style: "border-color:#8456C3" %>
        <div class="actions">
          <%= f.submit "Comment" , class: "btn btn-primary btn-raised" %>
        </div>
      <% end %>
    </div>

  </div>
</div>

<%= link_to 'Back', posts_path %>